# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41bc349ad39bf56810b5d9830031f5dc24d6c11cb364af3d9da8b7f4406eedbe752a59e342c7fc9ef8235740cff690048ffb67bc4514c3486c7d56417764951a

test:
  secret_key_base: eea36cb06af40ae5cdb8da5fd556d097ee1a554b7f6c64addd3bf5a4c092ce8159a16d6ee5cac39b3944c965f6fd1adce4fd18ef4374bce7a95d8bc3de6a6649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
